apiVersion: v1
kind: Service
metadata:
  name: clojure-berlin-2016
  labels:
    app: lens
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    service: clojure-berlin-2016
